-- 028_seed_yemen_institutions.sql
-- OWNING MODULE: organizations
--
-- Ten sample institutions per catalogue section -- private schools, government
-- schools, institutes, and colleges/universities -- spread across Sanaa, Aden,
-- Taiz, Hadramout and Shabwa. Enough rows to exercise the grid, the search
-- filter and the master-detail screen with realistic Yemeni data (principal,
-- landline, WhatsApp, neighbourhood, curriculum, seats).
--
-- Identifiers are deterministic: id = uuid_generate_v5(uuid_ns_url(),
-- 'madrasati:org:<slug>'), so each child row below resolves its parent by slug
-- and re-running the migration re-inserts nothing.
--
-- Logos live in design-prototype-v4/assets/logos/<slug>.svg and are produced
-- from the same source as this file, so a slug can never point at a missing asset.
--
-- Schools get their grade span linked in organization_stages; institutes and
-- higher-education institutions deliberately get none, because this platform's
-- academic ladder models SCHOOL grades (KG..3rd secondary) and claiming a
-- university teaches "3rd secondary" would be false data.
--
-- Idempotent: safe to re-run.

INSERT INTO organizations (
  id, name, slug, type, owner_user_id, description,
  governorate_id, governorate_code, district_id, district_code, neighborhood, address,
  phone, whatsapp, email, website, principal_name,
  curriculum, gender, image, verified, verification_status,
  registration_open, registration_status, seats_available,
  stages, languages, teaching_methods
)
SELECT
  uuid_generate_v5(uuid_ns_url(), 'madrasati:org:' || v.slug),
  v.name, v.slug, v.type, NULL, v.description,
  v.governorate_id, g.code, v.district_id, d.code, v.neighborhood, v.address,
  v.phone, v.whatsapp, v.email, v.website, v.principal_name,
  v.curriculum, v.gender, 'assets/logos/' || v.slug || '.svg', v.verified,
  CASE WHEN v.verified THEN 'verified' ELSE 'pending' END,
  true, 'open', v.seats,
  v.stages, '["AR","EN"]'::jsonb, '["ACTIVE","HYBRID"]'::jsonb
FROM (VALUES
  ('مدارس النهضة الأهلية', 'school-001', 'private_school', 'مدارس النهضة الأهلية مؤسسة تعليمية في محافظة صنعاء، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 1, 1, 'حي السبعين', 'محافظة صنعاء - حي السبعين', '+967-1-234501', '+967733101001', 'info@school-001.madrasati.test', 'https://school-001.madrasati.test', 'أ. عبدالله محمد الحكيمي', 'curriculum_ahli', 'female', 120, true, '["KG","PRIMARY","PREP","SECONDARY"]'::jsonb),
  ('مدارس الفيصل الأهلية', 'school-002', 'private_school', 'مدارس الفيصل الأهلية مؤسسة تعليمية في محافظة صنعاء، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 1, 2, 'حي معين', 'محافظة صنعاء - حي معين', '+967-1-234502', '+967733101002', 'info@school-002.madrasati.test', 'https://school-002.madrasati.test', 'أ. أحمد صالح المقطري', 'curriculum_ahli', 'male', 157, true, '["KG","PRIMARY","PREP","SECONDARY"]'::jsonb),
  ('مدارس الرواد الأهلية', 'school-003', 'private_school', 'مدارس الرواد الأهلية مؤسسة تعليمية في محافظة صنعاء، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 2, 5, 'حي الصافية', 'محافظة صنعاء - حي الصافية', '+967-1-234503', '+967733101003', 'info@school-003.madrasati.test', 'https://school-003.madrasati.test', 'أ. محمد عبده الشرعبي', 'curriculum_ahli', 'mixed', 194, true, '["PRIMARY","PREP","SECONDARY"]'::jsonb),
  ('مدارس الأمانة الأهلية', 'school-004', 'private_school', 'مدارس الأمانة الأهلية مؤسسة تعليمية في محافظة صنعاء، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 1, 3, 'حي شعوب', 'محافظة صنعاء - حي شعوب', '+967-1-234504', '+967733101004', 'info@school-004.madrasati.test', 'https://school-004.madrasati.test', 'أ. هدى علي الوصابي', 'curriculum_ahli', 'female', 231, false, '["KG","PRIMARY","PREP"]'::jsonb),
  ('مدارس المستقبل الأهلية', 'school-005', 'private_school', 'مدارس المستقبل الأهلية مؤسسة تعليمية في محافظة عدن، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 3, 16, 'حي خور مكسر', 'محافظة عدن - حي خور مكسر', '+967-2-234505', '+967733101005', 'info@school-005.madrasati.test', 'https://school-005.madrasati.test', 'أ. فهد ناصر العولقي', 'curriculum_ahli', 'male', 268, true, '["KG","PRIMARY","PREP","SECONDARY"]'::jsonb),
  ('مدارس البيان الأهلية', 'school-006', 'private_school', 'مدارس البيان الأهلية مؤسسة تعليمية في محافظة عدن، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 3, 18, 'حي المنصورة', 'محافظة عدن - حي المنصورة', '+967-2-234506', '+967733101006', 'info@school-006.madrasati.test', 'https://school-006.madrasati.test', 'أ. سامي عبدالرحمن بامطرف', 'curriculum_ahli', 'mixed', 305, true, '["PRIMARY","PREP","SECONDARY"]'::jsonb),
  ('مدارس النور الأهلية', 'school-007', 'private_school', 'مدارس النور الأهلية مؤسسة تعليمية في محافظة تعز، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 4, 21, 'حي المظفر', 'محافظة تعز - حي المظفر', '+967-4-234507', '+967733101007', 'info@school-007.madrasati.test', 'https://school-007.madrasati.test', 'أ. نبيل قائد سعيد', 'curriculum_ahli', 'female', 342, true, '["KG","PRIMARY","PREP","SECONDARY"]'::jsonb),
  ('مدارس اليمن الحديثة', 'school-008', 'private_school', 'مدارس اليمن الحديثة مؤسسة تعليمية في محافظة حضرموت، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 8, 35, 'حي المكلا', 'محافظة حضرموت - حي المكلا', '+967-5-234508', '+967733101008', 'info@school-008.madrasati.test', 'https://school-008.madrasati.test', 'أ. عمر سالم بن شملان', 'curriculum_dowali', 'male', 379, true, '["KG","PRIMARY","PREP","SECONDARY"]'::jsonb),
  ('مدارس الشرق الأهلية', 'school-009', 'private_school', 'مدارس الشرق الأهلية مؤسسة تعليمية في محافظة حضرموت، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 8, 36, 'حي سيئون', 'محافظة حضرموت - حي سيئون', '+967-5-234509', '+967733101009', 'info@school-009.madrasati.test', 'https://school-009.madrasati.test', 'أ. خالد عوض بارشيد', 'curriculum_ahli', 'mixed', 416, false, '["KG","PRIMARY","PREP"]'::jsonb),
  ('مدارس الجنوب الأهلية', 'school-010', 'private_school', 'مدارس الجنوب الأهلية مؤسسة تعليمية في محافظة شبوة، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 17, 54, 'حي عتق', 'محافظة شبوة - حي عتق', '+967-7-234510', '+967733101010', 'info@school-010.madrasati.test', 'https://school-010.madrasati.test', 'أ. صالح عيظة الحنشي', 'curriculum_ahli', 'female', 453, true, '["PRIMARY","PREP","SECONDARY"]'::jsonb),
  ('مدرسة الشهيد الحمدي الأساسية', 'gov-school-011', 'government_school', 'مدرسة الشهيد الحمدي الأساسية مؤسسة تعليمية في محافظة صنعاء، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 1, 1, 'حي السبعين', 'محافظة صنعاء - حي السبعين', '+967-1-345601', '+967711201001', 'info@gov-school-011.madrasati.test', 'https://gov-school-011.madrasati.test', 'أ. عبدالملك يحيى الشامي', 'curriculum_wazari', 'male', 490, true, '["PRIMARY","PREP"]'::jsonb),
  ('مدرسة الزبيري الأساسية', 'gov-school-012', 'government_school', 'مدرسة الزبيري الأساسية مؤسسة تعليمية في محافظة صنعاء، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 1, 2, 'حي معين', 'محافظة صنعاء - حي معين', '+967-1-345602', '+967711201002', 'info@gov-school-012.madrasati.test', 'https://gov-school-012.madrasati.test', 'أ. توفيق حسن العمراني', 'curriculum_wazari', 'mixed', 127, true, '["PRIMARY","PREP"]'::jsonb),
  ('مدرسة 26 سبتمبر الثانوية', 'gov-school-013', 'government_school', 'مدرسة 26 سبتمبر الثانوية مؤسسة تعليمية في محافظة صنعاء، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 1, 4, 'حي آزال', 'محافظة صنعاء - حي آزال', '+967-1-345603', '+967711201003', 'info@gov-school-013.madrasati.test', 'https://gov-school-013.madrasati.test', 'أ. علي محمد الأهدل', 'curriculum_wazari', 'female', 164, true, '["PRIMARY","PREP","SECONDARY"]'::jsonb),
  ('مدرسة الوحدة الأساسية', 'gov-school-014', 'government_school', 'مدرسة الوحدة الأساسية مؤسسة تعليمية في محافظة صنعاء، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 2, 6, 'حي الوحدة', 'محافظة صنعاء - حي الوحدة', '+967-1-345604', '+967711201004', 'info@gov-school-014.madrasati.test', 'https://gov-school-014.madrasati.test', 'أ. فاطمة أحمد الحاج', 'curriculum_wazari', 'male', 201, false, '["PRIMARY","PREP"]'::jsonb),
  ('مدرسة النصر الحكومية', 'gov-school-015', 'government_school', 'مدرسة النصر الحكومية مؤسسة تعليمية في محافظة عدن، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 3, 14, 'حي المعلا', 'محافظة عدن - حي المعلا', '+967-2-345605', '+967711201005', 'info@gov-school-015.madrasati.test', 'https://gov-school-015.madrasati.test', 'أ. جمال عبدالله السقاف', 'curriculum_wazari', 'mixed', 238, true, '["PRIMARY","PREP","SECONDARY"]'::jsonb),
  ('مدرسة الفاتح الأساسية', 'gov-school-016', 'government_school', 'مدرسة الفاتح الأساسية مؤسسة تعليمية في محافظة عدن، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 3, 17, 'حي الشيخ عثمان', 'محافظة عدن - حي الشيخ عثمان', '+967-2-345606', '+967711201006', 'info@gov-school-016.madrasati.test', 'https://gov-school-016.madrasati.test', 'أ. رشاد محمد باشراحيل', 'curriculum_wazari', 'female', 275, true, '["PRIMARY","PREP"]'::jsonb),
  ('مدرسة جمال عبدالناصر', 'gov-school-017', 'government_school', 'مدرسة جمال عبدالناصر مؤسسة تعليمية في محافظة تعز، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 4, 22, 'حي القاهرة', 'محافظة تعز - حي القاهرة', '+967-4-345607', '+967711201007', 'info@gov-school-017.madrasati.test', 'https://gov-school-017.madrasati.test', 'أ. عبده سعيد المخلافي', 'curriculum_wazari', 'male', 312, true, '["PRIMARY","PREP","SECONDARY"]'::jsonb),
  ('مدرسة تعز الأساسية', 'gov-school-018', 'government_school', 'مدرسة تعز الأساسية مؤسسة تعليمية في محافظة تعز، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 4, 23, 'حي صالة', 'محافظة تعز - حي صالة', '+967-4-345608', '+967711201008', 'info@gov-school-018.madrasati.test', 'https://gov-school-018.madrasati.test', 'أ. منى عبدالجليل ناجي', 'curriculum_wazari', 'mixed', 349, false, '["PRIMARY","PREP"]'::jsonb),
  ('مدرسة المكلا الأساسية', 'gov-school-019', 'government_school', 'مدرسة المكلا الأساسية مؤسسة تعليمية في محافظة حضرموت، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 8, 35, 'حي المكلا', 'محافظة حضرموت - حي المكلا', '+967-5-345609', '+967711201009', 'info@gov-school-019.madrasati.test', 'https://gov-school-019.madrasati.test', 'أ. سعيد عمر باجابر', 'curriculum_wazari', 'female', 386, true, '["KG","PRIMARY","PREP"]'::jsonb),
  ('مدرسة عتق الأساسية', 'gov-school-020', 'government_school', 'مدرسة عتق الأساسية مؤسسة تعليمية في محافظة شبوة، تقدم التعليم الأساسي والثانوي وفق المنهج المعتمد.', 17, 54, 'حي عتق', 'محافظة شبوة - حي عتق', '+967-7-345610', '+967711201010', 'info@gov-school-020.madrasati.test', 'https://gov-school-020.madrasati.test', 'أ. عوض محسن الحبتري', 'curriculum_wazari', 'male', 423, true, '["PRIMARY","PREP"]'::jsonb),
  ('معهد صنعاء التقني', 'institute-021', 'institute', 'معهد صنعاء التقني مؤسسة تدريب مهني وتقني في محافظة صنعاء، تمنح دبلومات في التخصصات المهنية.', 1, 1, 'حي السبعين', 'محافظة صنعاء - حي السبعين', '+967-1-456701', '+967735301001', 'info@institute-021.madrasati.test', 'https://institute-021.madrasati.test', 'د. غالب محمد الأنصاري', 'curriculum_wazari', 'mixed', 460, true, '[]'::jsonb),
  ('معهد الأمل للتدريب المهني', 'institute-022', 'institute', 'معهد الأمل للتدريب المهني مؤسسة تدريب مهني وتقني في محافظة صنعاء، تمنح دبلومات في التخصصات المهنية.', 1, 3, 'حي شعوب', 'محافظة صنعاء - حي شعوب', '+967-1-456702', '+967735301002', 'info@institute-022.madrasati.test', 'https://institute-022.madrasati.test', 'أ. لطف عبدالله صالح', 'curriculum_wazari', 'female', 497, true, '[]'::jsonb),
  ('معهد العلوم الصحية', 'institute-023', 'institute', 'معهد العلوم الصحية مؤسسة تدريب مهني وتقني في محافظة صنعاء، تمنح دبلومات في التخصصات المهنية.', 2, 5, 'حي الصافية', 'محافظة صنعاء - حي الصافية', '+967-1-456703', '+967735301003', 'info@institute-023.madrasati.test', 'https://institute-023.madrasati.test', 'د. أمل عبدالكريم الحكيمي', 'curriculum_wazari', 'male', 134, true, '[]'::jsonb),
  ('معهد البيان للحاسوب واللغات', 'institute-024', 'institute', 'معهد البيان للحاسوب واللغات مؤسسة تدريب مهني وتقني في محافظة صنعاء، تمنح دبلومات في التخصصات المهنية.', 1, 2, 'حي معين', 'محافظة صنعاء - حي معين', '+967-1-456704', '+967735301004', 'info@institute-024.madrasati.test', 'https://institute-024.madrasati.test', 'م. وليد أمين المقطري', 'curriculum_ahli', 'mixed', 171, false, '[]'::jsonb),
  ('معهد عدن التقني', 'institute-025', 'institute', 'معهد عدن التقني مؤسسة تدريب مهني وتقني في محافظة عدن، تمنح دبلومات في التخصصات المهنية.', 3, 16, 'حي خور مكسر', 'محافظة عدن - حي خور مكسر', '+967-2-456705', '+967735301005', 'info@institute-025.madrasati.test', 'https://institute-025.madrasati.test', 'د. عارف عبدالله بامخرمة', 'curriculum_wazari', 'female', 208, true, '[]'::jsonb),
  ('معهد عدن للعلوم الإدارية', 'institute-026', 'institute', 'معهد عدن للعلوم الإدارية مؤسسة تدريب مهني وتقني في محافظة عدن، تمنح دبلومات في التخصصات المهنية.', 3, 18, 'حي المنصورة', 'محافظة عدن - حي المنصورة', '+967-2-456706', '+967735301006', 'info@institute-026.madrasati.test', 'https://institute-026.madrasati.test', 'أ. سعاد ناصر الجفري', 'curriculum_wazari', 'male', 245, true, '[]'::jsonb),
  ('معهد تعز التقني', 'institute-027', 'institute', 'معهد تعز التقني مؤسسة تدريب مهني وتقني في محافظة تعز، تمنح دبلومات في التخصصات المهنية.', 4, 21, 'حي المظفر', 'محافظة تعز - حي المظفر', '+967-4-456707', '+967735301007', 'info@institute-027.madrasati.test', 'https://institute-027.madrasati.test', 'م. عبدالحميد قائد الشرعبي', 'curriculum_wazari', 'mixed', 282, true, '[]'::jsonb),
  ('معهد تعز للتدريب المهني', 'institute-028', 'institute', 'معهد تعز للتدريب المهني مؤسسة تدريب مهني وتقني في محافظة تعز، تمنح دبلومات في التخصصات المهنية.', 4, 22, 'حي القاهرة', 'محافظة تعز - حي القاهرة', '+967-4-456708', '+967735301008', 'info@institute-028.madrasati.test', 'https://institute-028.madrasati.test', 'أ. نجيب عبده سعيد', 'curriculum_wazari', 'female', 319, false, '[]'::jsonb),
  ('معهد حضرموت التقني', 'institute-029', 'institute', 'معهد حضرموت التقني مؤسسة تدريب مهني وتقني في محافظة حضرموت، تمنح دبلومات في التخصصات المهنية.', 8, 35, 'حي المكلا', 'محافظة حضرموت - حي المكلا', '+967-5-456709', '+967735301009', 'info@institute-029.madrasati.test', 'https://institute-029.madrasati.test', 'م. طارق سالم بن عفيف', 'curriculum_wazari', 'male', 356, true, '[]'::jsonb),
  ('معهد شبوة المهني', 'institute-030', 'institute', 'معهد شبوة المهني مؤسسة تدريب مهني وتقني في محافظة شبوة، تمنح دبلومات في التخصصات المهنية.', 17, 54, 'حي عتق', 'محافظة شبوة - حي عتق', '+967-7-456710', '+967735301010', 'info@institute-030.madrasati.test', 'https://institute-030.madrasati.test', 'أ. مراد علي باحميد', 'curriculum_wazari', 'mixed', 393, true, '[]'::jsonb),
  ('جامعة صنعاء الأهلية', 'university-031', 'university', 'جامعة صنعاء الأهلية مؤسسة تعليمية جامعية في محافظة صنعاء، تمنح الدرجات العلمية في التخصصات النظرية والتطبيقية.', 1, 1, 'حي السبعين', 'محافظة صنعاء - حي السبعين', '+967-1-567801', '+967737401001', 'info@university-031.madrasati.test', 'https://university-031.madrasati.test', 'أ.د. حمود محمد العزي', 'curriculum_wazari', 'female', 430, true, '[]'::jsonb),
  ('كلية العلوم الطبية - صنعاء', 'college-032', 'college', 'كلية العلوم الطبية - صنعاء مؤسسة تعليمية جامعية في محافظة صنعاء، تمنح الدرجات العلمية في التخصصات النظرية والتطبيقية.', 2, 5, 'حي الصافية', 'محافظة صنعاء - حي الصافية', '+967-1-567802', '+967737401002', 'info@college-032.madrasati.test', 'https://college-032.madrasati.test', 'أ.د. سامية عبدالوهاب الأغبري', 'curriculum_wazari', 'male', 467, true, '[]'::jsonb),
  ('جامعة العلوم والتكنولوجيا', 'university-033', 'university', 'جامعة العلوم والتكنولوجيا مؤسسة تعليمية جامعية في محافظة صنعاء، تمنح الدرجات العلمية في التخصصات النظرية والتطبيقية.', 1, 4, 'حي آزال', 'محافظة صنعاء - حي آزال', '+967-1-567803', '+967737401003', 'info@university-033.madrasati.test', 'https://university-033.madrasati.test', 'أ.د. عبدالرحمن محمد شمسان', 'curriculum_wazari', 'mixed', 504, true, '[]'::jsonb),
  ('كلية الحاسوب وتقنية المعلومات', 'college-034', 'college', 'كلية الحاسوب وتقنية المعلومات مؤسسة تعليمية جامعية في محافظة صنعاء، تمنح الدرجات العلمية في التخصصات النظرية والتطبيقية.', 1, 2, 'حي معين', 'محافظة صنعاء - حي معين', '+967-1-567804', '+967737401004', 'info@college-034.madrasati.test', 'https://college-034.madrasati.test', 'د. إبراهيم علي الحداد', 'curriculum_dowali', 'female', 141, true, '[]'::jsonb),
  ('جامعة عدن الأهلية', 'university-035', 'university', 'جامعة عدن الأهلية مؤسسة تعليمية جامعية في محافظة عدن، تمنح الدرجات العلمية في التخصصات النظرية والتطبيقية.', 3, 18, 'حي المنصورة', 'محافظة عدن - حي المنصورة', '+967-2-567805', '+967737401005', 'info@university-035.madrasati.test', 'https://university-035.madrasati.test', 'أ.د. عبدالكريم عمر الجفري', 'curriculum_wazari', 'male', 178, true, '[]'::jsonb),
  ('كلية الهندسة - عدن', 'college-036', 'college', 'كلية الهندسة - عدن مؤسسة تعليمية جامعية في محافظة عدن، تمنح الدرجات العلمية في التخصصات النظرية والتطبيقية.', 3, 16, 'حي خور مكسر', 'محافظة عدن - حي خور مكسر', '+967-2-567806', '+967737401006', 'info@college-036.madrasati.test', 'https://college-036.madrasati.test', 'أ.د. مهند سعيد باحشوان', 'curriculum_wazari', 'mixed', 215, true, '[]'::jsonb),
  ('كلية الاقتصاد - عدن', 'college-037', 'college', 'كلية الاقتصاد - عدن مؤسسة تعليمية جامعية في محافظة عدن، تمنح الدرجات العلمية في التخصصات النظرية والتطبيقية.', 3, 14, 'حي المعلا', 'محافظة عدن - حي المعلا', '+967-2-567807', '+967737401007', 'info@college-037.madrasati.test', 'https://college-037.madrasati.test', 'د. رانيا عبدالله السقاف', 'curriculum_wazari', 'female', 252, false, '[]'::jsonb),
  ('جامعة حضرموت الأهلية', 'university-038', 'university', 'جامعة حضرموت الأهلية مؤسسة تعليمية جامعية في محافظة حضرموت، تمنح الدرجات العلمية في التخصصات النظرية والتطبيقية.', 8, 35, 'حي المكلا', 'محافظة حضرموت - حي المكلا', '+967-5-567808', '+967737401008', 'info@university-038.madrasati.test', 'https://university-038.madrasati.test', 'أ.د. سالم عوض بامطرف', 'curriculum_wazari', 'male', 289, true, '[]'::jsonb),
  ('كلية المجتمع - حضرموت', 'college-039', 'college', 'كلية المجتمع - حضرموت مؤسسة تعليمية جامعية في محافظة حضرموت، تمنح الدرجات العلمية في التخصصات النظرية والتطبيقية.', 8, 36, 'حي سيئون', 'محافظة حضرموت - حي سيئون', '+967-5-567809', '+967737401009', 'info@college-039.madrasati.test', 'https://college-039.madrasati.test', 'د. هاني عمر باجابر', 'curriculum_wazari', 'mixed', 326, true, '[]'::jsonb),
  ('كلية شبوة للعلوم التطبيقية', 'college-040', 'college', 'كلية شبوة للعلوم التطبيقية مؤسسة تعليمية جامعية في محافظة شبوة، تمنح الدرجات العلمية في التخصصات النظرية والتطبيقية.', 17, 54, 'حي عتق', 'محافظة شبوة - حي عتق', '+967-7-567810', '+967737401010', 'info@college-040.madrasati.test', 'https://college-040.madrasati.test', 'د. ناصر عيظة الحنشي', 'curriculum_wazari', 'female', 363, true, '[]'::jsonb)
) AS v(name, slug, type, description, governorate_id, district_id, neighborhood,
       address, phone, whatsapp, email, website, principal_name, curriculum,
       gender, seats, verified, stages)
JOIN locations_governorates g ON g.id = v.governorate_id
JOIN locations_districts d ON d.id = v.district_id
ON CONFLICT (id) DO NOTHING;

-- ---------- grade spans served ----------
INSERT INTO organization_stages (organization_id, stage_id, delivery_mode, capacity, current_students)
SELECT o.id, s.id, v.delivery_mode, v.capacity, v.current_students
FROM (VALUES
  ('school-001', 'KG', 'on_site', 120, 54),
  ('school-001', 'PRIMARY', 'hybrid', 143, 78),
  ('school-001', 'PREP', 'on_site', 166, 107),
  ('school-001', 'SECONDARY', 'on_site', 189, 141),
  ('school-002', 'KG', 'hybrid', 157, 86),
  ('school-002', 'PRIMARY', 'on_site', 180, 117),
  ('school-002', 'PREP', 'on_site', 203, 152),
  ('school-002', 'SECONDARY', 'hybrid', 226, 192),
  ('school-003', 'PRIMARY', 'on_site', 194, 126),
  ('school-003', 'PREP', 'on_site', 217, 162),
  ('school-003', 'SECONDARY', 'hybrid', 240, 204),
  ('school-004', 'KG', 'on_site', 231, 173),
  ('school-004', 'PRIMARY', 'hybrid', 254, 215),
  ('school-004', 'PREP', 'on_site', 277, 124),
  ('school-005', 'KG', 'hybrid', 268, 227),
  ('school-005', 'PRIMARY', 'on_site', 291, 130),
  ('school-005', 'PREP', 'on_site', 314, 172),
  ('school-005', 'SECONDARY', 'hybrid', 337, 219),
  ('school-006', 'PRIMARY', 'on_site', 305, 137),
  ('school-006', 'PREP', 'on_site', 328, 180),
  ('school-006', 'SECONDARY', 'hybrid', 351, 228),
  ('school-007', 'KG', 'on_site', 342, 188),
  ('school-007', 'PRIMARY', 'hybrid', 365, 237),
  ('school-007', 'PREP', 'on_site', 128, 96),
  ('school-007', 'SECONDARY', 'on_site', 151, 128),
  ('school-008', 'KG', 'hybrid', 379, 246),
  ('school-008', 'PRIMARY', 'on_site', 142, 106),
  ('school-008', 'PREP', 'on_site', 165, 140),
  ('school-008', 'SECONDARY', 'hybrid', 188, 84),
  ('school-009', 'KG', 'on_site', 156, 117),
  ('school-009', 'PRIMARY', 'on_site', 179, 152),
  ('school-009', 'PREP', 'hybrid', 202, 90),
  ('school-010', 'PRIMARY', 'on_site', 193, 164),
  ('school-010', 'PREP', 'hybrid', 216, 97),
  ('school-010', 'SECONDARY', 'on_site', 239, 131),
  ('gov-school-011', 'PRIMARY', 'hybrid', 230, 103),
  ('gov-school-011', 'PREP', 'on_site', 253, 139),
  ('gov-school-012', 'PRIMARY', 'on_site', 267, 146),
  ('gov-school-012', 'PREP', 'on_site', 290, 188),
  ('gov-school-013', 'PRIMARY', 'on_site', 304, 197),
  ('gov-school-013', 'PREP', 'hybrid', 327, 245),
  ('gov-school-013', 'SECONDARY', 'on_site', 350, 297),
  ('gov-school-014', 'PRIMARY', 'hybrid', 341, 255),
  ('gov-school-014', 'PREP', 'on_site', 364, 309),
  ('gov-school-015', 'PRIMARY', 'on_site', 378, 321),
  ('gov-school-015', 'PREP', 'on_site', 141, 63),
  ('gov-school-015', 'SECONDARY', 'hybrid', 164, 90),
  ('gov-school-016', 'PRIMARY', 'on_site', 155, 69),
  ('gov-school-016', 'PREP', 'hybrid', 178, 97),
  ('gov-school-017', 'PRIMARY', 'hybrid', 192, 105),
  ('gov-school-017', 'PREP', 'on_site', 215, 139),
  ('gov-school-017', 'SECONDARY', 'on_site', 238, 178),
  ('gov-school-018', 'PRIMARY', 'on_site', 229, 148),
  ('gov-school-018', 'PREP', 'on_site', 252, 189),
  ('gov-school-019', 'KG', 'on_site', 266, 199),
  ('gov-school-019', 'PRIMARY', 'hybrid', 289, 245),
  ('gov-school-019', 'PREP', 'on_site', 312, 140),
  ('gov-school-020', 'PRIMARY', 'hybrid', 303, 257),
  ('gov-school-020', 'PREP', 'on_site', 326, 146)
) AS v(slug, stage_code, delivery_mode, capacity, current_students)
JOIN organizations o ON o.slug = v.slug
JOIN academic_stages s ON s.code = v.stage_code
ON CONFLICT (organization_id, stage_id) DO NOTHING;

-- ---------- subjects taught ----------
INSERT INTO organization_subjects (organization_id, subject_id)
SELECT o.id, v.subject_id
FROM (VALUES
  ('school-001', 1),
  ('school-001', 2),
  ('school-001', 3),
  ('school-001', 4),
  ('school-001', 5),
  ('school-001', 9),
  ('school-001', 10),
  ('school-002', 1),
  ('school-002', 2),
  ('school-002', 3),
  ('school-002', 4),
  ('school-002', 5),
  ('school-002', 9),
  ('school-002', 10),
  ('school-003', 1),
  ('school-003', 2),
  ('school-003', 3),
  ('school-003', 4),
  ('school-003', 5),
  ('school-003', 9),
  ('school-003', 10),
  ('school-004', 1),
  ('school-004', 2),
  ('school-004', 3),
  ('school-004', 4),
  ('school-004', 5),
  ('school-004', 9),
  ('school-004', 10),
  ('school-005', 1),
  ('school-005', 2),
  ('school-005', 3),
  ('school-005', 4),
  ('school-005', 5),
  ('school-005', 9),
  ('school-005', 10),
  ('school-006', 1),
  ('school-006', 2),
  ('school-006', 3),
  ('school-006', 4),
  ('school-006', 5),
  ('school-006', 9),
  ('school-006', 10),
  ('school-007', 1),
  ('school-007', 2),
  ('school-007', 3),
  ('school-007', 4),
  ('school-007', 5),
  ('school-007', 9),
  ('school-007', 10),
  ('school-008', 1),
  ('school-008', 2),
  ('school-008', 3),
  ('school-008', 4),
  ('school-008', 5),
  ('school-008', 9),
  ('school-008', 10),
  ('school-009', 1),
  ('school-009', 2),
  ('school-009', 3),
  ('school-009', 4),
  ('school-009', 5),
  ('school-009', 9),
  ('school-009', 10),
  ('school-010', 1),
  ('school-010', 2),
  ('school-010', 3),
  ('school-010', 4),
  ('school-010', 5),
  ('school-010', 9),
  ('school-010', 10),
  ('gov-school-011', 1),
  ('gov-school-011', 2),
  ('gov-school-011', 3),
  ('gov-school-011', 4),
  ('gov-school-011', 5),
  ('gov-school-011', 9),
  ('gov-school-012', 1),
  ('gov-school-012', 2),
  ('gov-school-012', 3),
  ('gov-school-012', 4),
  ('gov-school-012', 5),
  ('gov-school-012', 9),
  ('gov-school-013', 1),
  ('gov-school-013', 2),
  ('gov-school-013', 3),
  ('gov-school-013', 4),
  ('gov-school-013', 5),
  ('gov-school-013', 9),
  ('gov-school-014', 1),
  ('gov-school-014', 2),
  ('gov-school-014', 3),
  ('gov-school-014', 4),
  ('gov-school-014', 5),
  ('gov-school-014', 9),
  ('gov-school-015', 1),
  ('gov-school-015', 2),
  ('gov-school-015', 3),
  ('gov-school-015', 4),
  ('gov-school-015', 5),
  ('gov-school-015', 9),
  ('gov-school-016', 1),
  ('gov-school-016', 2),
  ('gov-school-016', 3),
  ('gov-school-016', 4),
  ('gov-school-016', 5),
  ('gov-school-016', 9),
  ('gov-school-017', 1),
  ('gov-school-017', 2),
  ('gov-school-017', 3),
  ('gov-school-017', 4),
  ('gov-school-017', 5),
  ('gov-school-017', 9),
  ('gov-school-018', 1),
  ('gov-school-018', 2),
  ('gov-school-018', 3),
  ('gov-school-018', 4),
  ('gov-school-018', 5),
  ('gov-school-018', 9),
  ('gov-school-019', 1),
  ('gov-school-019', 2),
  ('gov-school-019', 3),
  ('gov-school-019', 4),
  ('gov-school-019', 5),
  ('gov-school-019', 9),
  ('gov-school-020', 1),
  ('gov-school-020', 2),
  ('gov-school-020', 3),
  ('gov-school-020', 4),
  ('gov-school-020', 5),
  ('gov-school-020', 9),
  ('institute-021', 3),
  ('institute-021', 4),
  ('institute-021', 9),
  ('institute-021', 10),
  ('institute-022', 3),
  ('institute-022', 4),
  ('institute-022', 9),
  ('institute-022', 10),
  ('institute-023', 3),
  ('institute-023', 4),
  ('institute-023', 9),
  ('institute-023', 10),
  ('institute-024', 3),
  ('institute-024', 4),
  ('institute-024', 9),
  ('institute-024', 10),
  ('institute-025', 3),
  ('institute-025', 4),
  ('institute-025', 9),
  ('institute-025', 10),
  ('institute-026', 3),
  ('institute-026', 4),
  ('institute-026', 9),
  ('institute-026', 10),
  ('institute-027', 3),
  ('institute-027', 4),
  ('institute-027', 9),
  ('institute-027', 10),
  ('institute-028', 3),
  ('institute-028', 4),
  ('institute-028', 9),
  ('institute-028', 10),
  ('institute-029', 3),
  ('institute-029', 4),
  ('institute-029', 9),
  ('institute-029', 10),
  ('institute-030', 3),
  ('institute-030', 4),
  ('institute-030', 9),
  ('institute-030', 10),
  ('university-031', 3),
  ('university-031', 9),
  ('university-031', 4),
  ('university-031', 6),
  ('university-031', 7),
  ('university-031', 8),
  ('university-031', 10),
  ('college-032', 3),
  ('college-032', 9),
  ('college-032', 4),
  ('college-032', 6),
  ('college-032', 7),
  ('college-032', 8),
  ('college-032', 10),
  ('university-033', 3),
  ('university-033', 9),
  ('university-033', 4),
  ('university-033', 6),
  ('university-033', 7),
  ('university-033', 8),
  ('university-033', 10),
  ('college-034', 3),
  ('college-034', 9),
  ('college-034', 4),
  ('college-034', 6),
  ('college-034', 7),
  ('college-034', 8),
  ('college-034', 10),
  ('university-035', 3),
  ('university-035', 9),
  ('university-035', 4),
  ('university-035', 6),
  ('university-035', 7),
  ('university-035', 8),
  ('university-035', 10),
  ('college-036', 3),
  ('college-036', 9),
  ('college-036', 4),
  ('college-036', 6),
  ('college-036', 7),
  ('college-036', 8),
  ('college-036', 10),
  ('college-037', 3),
  ('college-037', 9),
  ('college-037', 4),
  ('college-037', 6),
  ('college-037', 7),
  ('college-037', 8),
  ('college-037', 10),
  ('university-038', 3),
  ('university-038', 9),
  ('university-038', 4),
  ('university-038', 6),
  ('university-038', 7),
  ('university-038', 8),
  ('university-038', 10),
  ('college-039', 3),
  ('college-039', 9),
  ('college-039', 4),
  ('college-039', 6),
  ('college-039', 7),
  ('college-039', 8),
  ('college-039', 10),
  ('college-040', 3),
  ('college-040', 9),
  ('college-040', 4),
  ('college-040', 6),
  ('college-040', 7),
  ('college-040', 8),
  ('college-040', 10)
) AS v(slug, subject_id)
JOIN organizations o ON o.slug = v.slug
ON CONFLICT (organization_id, subject_id) DO NOTHING;

-- ---------- teaching methods ----------
INSERT INTO organization_teaching_methods (organization_id, teaching_method_id)
SELECT o.id, m.id
FROM (VALUES
  ('school-001', 'ACTIVE'),
  ('school-001', 'HYBRID'),
  ('school-001', 'MONTESSORI'),
  ('school-002', 'ACTIVE'),
  ('school-002', 'HYBRID'),
  ('school-002', 'MONTESSORI'),
  ('school-003', 'ACTIVE'),
  ('school-003', 'HYBRID'),
  ('school-003', 'MONTESSORI'),
  ('school-004', 'ACTIVE'),
  ('school-004', 'HYBRID'),
  ('school-004', 'MONTESSORI'),
  ('school-005', 'ACTIVE'),
  ('school-005', 'HYBRID'),
  ('school-005', 'MONTESSORI'),
  ('school-006', 'ACTIVE'),
  ('school-006', 'HYBRID'),
  ('school-006', 'MONTESSORI'),
  ('school-007', 'ACTIVE'),
  ('school-007', 'HYBRID'),
  ('school-007', 'MONTESSORI'),
  ('school-008', 'ACTIVE'),
  ('school-008', 'HYBRID'),
  ('school-008', 'MONTESSORI'),
  ('school-009', 'ACTIVE'),
  ('school-009', 'HYBRID'),
  ('school-009', 'MONTESSORI'),
  ('school-010', 'ACTIVE'),
  ('school-010', 'HYBRID'),
  ('school-010', 'MONTESSORI'),
  ('gov-school-011', 'TRAD'),
  ('gov-school-011', 'ACTIVE'),
  ('gov-school-012', 'TRAD'),
  ('gov-school-012', 'ACTIVE'),
  ('gov-school-013', 'TRAD'),
  ('gov-school-013', 'ACTIVE'),
  ('gov-school-014', 'TRAD'),
  ('gov-school-014', 'ACTIVE'),
  ('gov-school-015', 'TRAD'),
  ('gov-school-015', 'ACTIVE'),
  ('gov-school-016', 'TRAD'),
  ('gov-school-016', 'ACTIVE'),
  ('gov-school-017', 'TRAD'),
  ('gov-school-017', 'ACTIVE'),
  ('gov-school-018', 'TRAD'),
  ('gov-school-018', 'ACTIVE'),
  ('gov-school-019', 'TRAD'),
  ('gov-school-019', 'ACTIVE'),
  ('gov-school-020', 'TRAD'),
  ('gov-school-020', 'ACTIVE'),
  ('institute-021', 'TRAD'),
  ('institute-021', 'ACTIVE'),
  ('institute-021', 'ONLINE'),
  ('institute-022', 'TRAD'),
  ('institute-022', 'ACTIVE'),
  ('institute-022', 'ONLINE'),
  ('institute-023', 'TRAD'),
  ('institute-023', 'ACTIVE'),
  ('institute-023', 'ONLINE'),
  ('institute-024', 'TRAD'),
  ('institute-024', 'ACTIVE'),
  ('institute-024', 'ONLINE'),
  ('institute-025', 'TRAD'),
  ('institute-025', 'ACTIVE'),
  ('institute-025', 'ONLINE'),
  ('institute-026', 'TRAD'),
  ('institute-026', 'ACTIVE'),
  ('institute-026', 'ONLINE'),
  ('institute-027', 'TRAD'),
  ('institute-027', 'ACTIVE'),
  ('institute-027', 'ONLINE'),
  ('institute-028', 'TRAD'),
  ('institute-028', 'ACTIVE'),
  ('institute-028', 'ONLINE'),
  ('institute-029', 'TRAD'),
  ('institute-029', 'ACTIVE'),
  ('institute-029', 'ONLINE'),
  ('institute-030', 'TRAD'),
  ('institute-030', 'ACTIVE'),
  ('institute-030', 'ONLINE'),
  ('university-031', 'TRAD'),
  ('university-031', 'ACTIVE'),
  ('university-031', 'ONLINE'),
  ('university-031', 'HYBRID'),
  ('college-032', 'TRAD'),
  ('college-032', 'ACTIVE'),
  ('college-032', 'HYBRID'),
  ('university-033', 'TRAD'),
  ('university-033', 'ACTIVE'),
  ('university-033', 'ONLINE'),
  ('university-033', 'HYBRID'),
  ('college-034', 'TRAD'),
  ('college-034', 'ACTIVE'),
  ('college-034', 'HYBRID'),
  ('university-035', 'TRAD'),
  ('university-035', 'ACTIVE'),
  ('university-035', 'ONLINE'),
  ('university-035', 'HYBRID'),
  ('college-036', 'TRAD'),
  ('college-036', 'ACTIVE'),
  ('college-036', 'HYBRID'),
  ('college-037', 'TRAD'),
  ('college-037', 'ACTIVE'),
  ('college-037', 'HYBRID'),
  ('university-038', 'TRAD'),
  ('university-038', 'ACTIVE'),
  ('university-038', 'ONLINE'),
  ('university-038', 'HYBRID'),
  ('college-039', 'TRAD'),
  ('college-039', 'ACTIVE'),
  ('college-039', 'HYBRID'),
  ('college-040', 'TRAD'),
  ('college-040', 'ACTIVE'),
  ('college-040', 'HYBRID')
) AS v(slug, method_code)
JOIN organizations o ON o.slug = v.slug
JOIN teaching_methods m ON m.code = v.method_code
ON CONFLICT (organization_id, teaching_method_id) DO NOTHING;

-- ---------- published fees (org-scoped) ----------
INSERT INTO organization_fees (organization_id, fee_type, name, description, amount, currency, frequency, visibility)
SELECT o.id, v.fee_type, v.name, v.description, v.amount, 'YER', v.frequency, 'authenticated'
FROM (VALUES
  ('school-001', 'registration', 'رسوم التسجيل', 'رسوم تسجيل تُدفع مرة واحدة عند الالتحاق.', 45000, 'once'),
  ('school-001', 'tuition', 'القسط الدراسي السنوي', 'القسط الدراسي للعام الحالي.', 180000, 'yearly'),
  ('school-001', 'transport', 'رسوم النقل المدرسي', 'اشتراك النقل من وإلى المدرسة.', 18000, 'yearly'),
  ('school-002', 'registration', 'رسوم التسجيل', 'رسوم تسجيل تُدفع مرة واحدة عند الالتحاق.', 52300, 'once'),
  ('school-002', 'tuition', 'القسط الدراسي السنوي', 'القسط الدراسي للعام الحالي.', 209200, 'yearly'),
  ('school-002', 'transport', 'رسوم النقل المدرسي', 'اشتراك النقل من وإلى المدرسة.', 20000, 'yearly'),
  ('school-003', 'registration', 'رسوم التسجيل', 'رسوم تسجيل تُدفع مرة واحدة عند الالتحاق.', 59600, 'once'),
  ('school-003', 'tuition', 'القسط الدراسي السنوي', 'القسط الدراسي للعام الحالي.', 238400, 'yearly'),
  ('school-003', 'transport', 'رسوم النقل المدرسي', 'اشتراك النقل من وإلى المدرسة.', 22000, 'yearly'),
  ('school-004', 'registration', 'رسوم التسجيل', 'رسوم تسجيل تُدفع مرة واحدة عند الالتحاق.', 66900, 'once'),
  ('school-004', 'tuition', 'القسط الدراسي السنوي', 'القسط الدراسي للعام الحالي.', 267600, 'yearly'),
  ('school-004', 'transport', 'رسوم النقل المدرسي', 'اشتراك النقل من وإلى المدرسة.', 24000, 'yearly'),
  ('school-005', 'registration', 'رسوم التسجيل', 'رسوم تسجيل تُدفع مرة واحدة عند الالتحاق.', 74200, 'once'),
  ('school-005', 'tuition', 'القسط الدراسي السنوي', 'القسط الدراسي للعام الحالي.', 296800, 'yearly'),
  ('school-005', 'transport', 'رسوم النقل المدرسي', 'اشتراك النقل من وإلى المدرسة.', 26000, 'yearly'),
  ('school-006', 'registration', 'رسوم التسجيل', 'رسوم تسجيل تُدفع مرة واحدة عند الالتحاق.', 81500, 'once'),
  ('school-006', 'tuition', 'القسط الدراسي السنوي', 'القسط الدراسي للعام الحالي.', 326000, 'yearly'),
  ('school-006', 'transport', 'رسوم النقل المدرسي', 'اشتراك النقل من وإلى المدرسة.', 18000, 'yearly'),
  ('school-007', 'registration', 'رسوم التسجيل', 'رسوم تسجيل تُدفع مرة واحدة عند الالتحاق.', 88800, 'once'),
  ('school-007', 'tuition', 'القسط الدراسي السنوي', 'القسط الدراسي للعام الحالي.', 355200, 'yearly'),
  ('school-007', 'transport', 'رسوم النقل المدرسي', 'اشتراك النقل من وإلى المدرسة.', 20000, 'yearly'),
  ('school-008', 'registration', 'رسوم التسجيل', 'رسوم تسجيل تُدفع مرة واحدة عند الالتحاق.', 96100, 'once'),
  ('school-008', 'tuition', 'القسط الدراسي السنوي', 'القسط الدراسي للعام الحالي.', 384400, 'yearly'),
  ('school-008', 'transport', 'رسوم النقل المدرسي', 'اشتراك النقل من وإلى المدرسة.', 22000, 'yearly'),
  ('school-009', 'registration', 'رسوم التسجيل', 'رسوم تسجيل تُدفع مرة واحدة عند الالتحاق.', 103400, 'once'),
  ('school-009', 'tuition', 'القسط الدراسي السنوي', 'القسط الدراسي للعام الحالي.', 413600, 'yearly'),
  ('school-009', 'transport', 'رسوم النقل المدرسي', 'اشتراك النقل من وإلى المدرسة.', 24000, 'yearly'),
  ('school-010', 'registration', 'رسوم التسجيل', 'رسوم تسجيل تُدفع مرة واحدة عند الالتحاق.', 110700, 'once'),
  ('school-010', 'tuition', 'القسط الدراسي السنوي', 'القسط الدراسي للعام الحالي.', 442800, 'yearly'),
  ('school-010', 'transport', 'رسوم النقل المدرسي', 'اشتراك النقل من وإلى المدرسة.', 26000, 'yearly'),
  ('gov-school-011', 'registration', 'رسوم التسجيل', 'رسوم رمزية تُدفع عند التسجيل.', 2000, 'once'),
  ('gov-school-011', 'activity', 'رسوم الأنشطة', 'مساهمة الأنشطة الطلابية.', 7000, 'yearly'),
  ('gov-school-012', 'registration', 'رسوم التسجيل', 'رسوم رمزية تُدفع عند التسجيل.', 2000, 'once'),
  ('gov-school-012', 'activity', 'رسوم الأنشطة', 'مساهمة الأنشطة الطلابية.', 8000, 'yearly'),
  ('gov-school-013', 'registration', 'رسوم التسجيل', 'رسوم رمزية تُدفع عند التسجيل.', 2000, 'once'),
  ('gov-school-013', 'activity', 'رسوم الأنشطة', 'مساهمة الأنشطة الطلابية.', 5000, 'yearly'),
  ('gov-school-014', 'registration', 'رسوم التسجيل', 'رسوم رمزية تُدفع عند التسجيل.', 2000, 'once'),
  ('gov-school-014', 'activity', 'رسوم الأنشطة', 'مساهمة الأنشطة الطلابية.', 6000, 'yearly'),
  ('gov-school-015', 'registration', 'رسوم التسجيل', 'رسوم رمزية تُدفع عند التسجيل.', 2000, 'once'),
  ('gov-school-015', 'activity', 'رسوم الأنشطة', 'مساهمة الأنشطة الطلابية.', 7000, 'yearly'),
  ('gov-school-016', 'registration', 'رسوم التسجيل', 'رسوم رمزية تُدفع عند التسجيل.', 2000, 'once'),
  ('gov-school-016', 'activity', 'رسوم الأنشطة', 'مساهمة الأنشطة الطلابية.', 8000, 'yearly'),
  ('gov-school-017', 'registration', 'رسوم التسجيل', 'رسوم رمزية تُدفع عند التسجيل.', 2000, 'once'),
  ('gov-school-017', 'activity', 'رسوم الأنشطة', 'مساهمة الأنشطة الطلابية.', 5000, 'yearly'),
  ('gov-school-018', 'registration', 'رسوم التسجيل', 'رسوم رمزية تُدفع عند التسجيل.', 2000, 'once'),
  ('gov-school-018', 'activity', 'رسوم الأنشطة', 'مساهمة الأنشطة الطلابية.', 6000, 'yearly'),
  ('gov-school-019', 'registration', 'رسوم التسجيل', 'رسوم رمزية تُدفع عند التسجيل.', 2000, 'once'),
  ('gov-school-019', 'activity', 'رسوم الأنشطة', 'مساهمة الأنشطة الطلابية.', 7000, 'yearly'),
  ('gov-school-020', 'registration', 'رسوم التسجيل', 'رسوم رمزية تُدفع عند التسجيل.', 2000, 'once'),
  ('gov-school-020', 'activity', 'رسوم الأنشطة', 'مساهمة الأنشطة الطلابية.', 8000, 'yearly'),
  ('institute-021', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الدبلوم.', 101000, 'once'),
  ('institute-021', 'tuition', 'رسوم الفصل التدريبي', 'رسوم كل فصل من فصول الدبلوم.', 202000, 'term'),
  ('institute-021', 'lab', 'رسوم المعامل', 'رسوم استخدام المعامل التخصصية.', 12000, 'term'),
  ('institute-022', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الدبلوم.', 108300, 'once'),
  ('institute-022', 'tuition', 'رسوم الفصل التدريبي', 'رسوم كل فصل من فصول الدبلوم.', 216600, 'term'),
  ('institute-022', 'lab', 'رسوم المعامل', 'رسوم استخدام المعامل التخصصية.', 13500, 'term'),
  ('institute-023', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الدبلوم.', 115600, 'once'),
  ('institute-023', 'tuition', 'رسوم الفصل التدريبي', 'رسوم كل فصل من فصول الدبلوم.', 231200, 'term'),
  ('institute-023', 'lab', 'رسوم المعامل', 'رسوم استخدام المعامل التخصصية.', 15000, 'term'),
  ('institute-024', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الدبلوم.', 122900, 'once'),
  ('institute-024', 'tuition', 'رسوم الفصل التدريبي', 'رسوم كل فصل من فصول الدبلوم.', 245800, 'term'),
  ('institute-024', 'lab', 'رسوم المعامل', 'رسوم استخدام المعامل التخصصية.', 16500, 'term'),
  ('institute-025', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الدبلوم.', 130200, 'once'),
  ('institute-025', 'tuition', 'رسوم الفصل التدريبي', 'رسوم كل فصل من فصول الدبلوم.', 260400, 'term'),
  ('institute-025', 'lab', 'رسوم المعامل', 'رسوم استخدام المعامل التخصصية.', 18000, 'term'),
  ('institute-026', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الدبلوم.', 47500, 'once'),
  ('institute-026', 'tuition', 'رسوم الفصل التدريبي', 'رسوم كل فصل من فصول الدبلوم.', 95000, 'term'),
  ('institute-026', 'lab', 'رسوم المعامل', 'رسوم استخدام المعامل التخصصية.', 12000, 'term'),
  ('institute-027', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الدبلوم.', 54800, 'once'),
  ('institute-027', 'tuition', 'رسوم الفصل التدريبي', 'رسوم كل فصل من فصول الدبلوم.', 109600, 'term'),
  ('institute-027', 'lab', 'رسوم المعامل', 'رسوم استخدام المعامل التخصصية.', 13500, 'term'),
  ('institute-028', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الدبلوم.', 62100, 'once'),
  ('institute-028', 'tuition', 'رسوم الفصل التدريبي', 'رسوم كل فصل من فصول الدبلوم.', 124200, 'term'),
  ('institute-028', 'lab', 'رسوم المعامل', 'رسوم استخدام المعامل التخصصية.', 15000, 'term'),
  ('institute-029', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الدبلوم.', 69400, 'once'),
  ('institute-029', 'tuition', 'رسوم الفصل التدريبي', 'رسوم كل فصل من فصول الدبلوم.', 138800, 'term'),
  ('institute-029', 'lab', 'رسوم المعامل', 'رسوم استخدام المعامل التخصصية.', 16500, 'term'),
  ('institute-030', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الدبلوم.', 76700, 'once'),
  ('institute-030', 'tuition', 'رسوم الفصل التدريبي', 'رسوم كل فصل من فصول الدبلوم.', 153400, 'term'),
  ('institute-030', 'lab', 'رسوم المعامل', 'رسوم استخدام المعامل التخصصية.', 18000, 'term'),
  ('university-031', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الطالب الجديد.', 168000, 'once'),
  ('university-031', 'tuition', 'رسوم الساعة المعتمدة', 'رسوم لكل ساعة معتمدة.', 9000, 'term'),
  ('university-031', 'lab', 'رسوم المعامل', 'رسوم المقررات العملية.', 15000, 'term'),
  ('college-032', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الطالب الجديد.', 182600, 'once'),
  ('college-032', 'tuition', 'رسوم الساعة المعتمدة', 'رسوم لكل ساعة معتمدة.', 10200, 'term'),
  ('college-032', 'lab', 'رسوم المعامل', 'رسوم المقررات العملية.', 17000, 'term'),
  ('university-033', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الطالب الجديد.', 197200, 'once'),
  ('university-033', 'tuition', 'رسوم الساعة المعتمدة', 'رسوم لكل ساعة معتمدة.', 11400, 'term'),
  ('university-033', 'lab', 'رسوم المعامل', 'رسوم المقررات العملية.', 19000, 'term'),
  ('college-034', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الطالب الجديد.', 211800, 'once'),
  ('college-034', 'tuition', 'رسوم الساعة المعتمدة', 'رسوم لكل ساعة معتمدة.', 12600, 'term'),
  ('college-034', 'lab', 'رسوم المعامل', 'رسوم المقررات العملية.', 21000, 'term'),
  ('university-035', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الطالب الجديد.', 226400, 'once'),
  ('university-035', 'tuition', 'رسوم الساعة المعتمدة', 'رسوم لكل ساعة معتمدة.', 13800, 'term'),
  ('university-035', 'lab', 'رسوم المعامل', 'رسوم المقررات العملية.', 23000, 'term'),
  ('college-036', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الطالب الجديد.', 241000, 'once'),
  ('college-036', 'tuition', 'رسوم الساعة المعتمدة', 'رسوم لكل ساعة معتمدة.', 15000, 'term'),
  ('college-036', 'lab', 'رسوم المعامل', 'رسوم المقررات العملية.', 15000, 'term'),
  ('college-037', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الطالب الجديد.', 255600, 'once'),
  ('college-037', 'tuition', 'رسوم الساعة المعتمدة', 'رسوم لكل ساعة معتمدة.', 9000, 'term'),
  ('college-037', 'lab', 'رسوم المعامل', 'رسوم المقررات العملية.', 17000, 'term'),
  ('university-038', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الطالب الجديد.', 90200, 'once'),
  ('university-038', 'tuition', 'رسوم الساعة المعتمدة', 'رسوم لكل ساعة معتمدة.', 10200, 'term'),
  ('university-038', 'lab', 'رسوم المعامل', 'رسوم المقررات العملية.', 19000, 'term'),
  ('college-039', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الطالب الجديد.', 104800, 'once'),
  ('college-039', 'tuition', 'رسوم الساعة المعتمدة', 'رسوم لكل ساعة معتمدة.', 11400, 'term'),
  ('college-039', 'lab', 'رسوم المعامل', 'رسوم المقررات العملية.', 21000, 'term'),
  ('college-040', 'registration', 'رسوم التسجيل', 'رسوم تسجيل الطالب الجديد.', 119400, 'once'),
  ('college-040', 'tuition', 'رسوم الساعة المعتمدة', 'رسوم لكل ساعة معتمدة.', 12600, 'term'),
  ('college-040', 'lab', 'رسوم المعامل', 'رسوم المقررات العملية.', 23000, 'term')
) AS v(slug, fee_type, name, description, amount, frequency)
JOIN organizations o ON o.slug = v.slug
ON CONFLICT (organization_id, fee_type, name)
  WHERE grade_id IS NULL AND stage_id IS NULL AND deleted_at IS NULL
  DO NOTHING;
