// AUTO-GENERATED by scripts/media-map-build.js — explicit entity id -> existing asset mapping.
// The database id is the entity identity; label/slug is display-only. Do not edit by hand.
window.MADRASATI_MEDIA_MAP = {
  "generatedAt": "2026-09-26T16:32:24.148Z",
  "organizations": {
    "cfeffce8-4908-5490-b768-f812ca4bbf4c": {
      "type": "university",
      "label": "university-031",
      "logo": "assets/logos/university-031.svg",
      "cover": null,
      "gallery": []
    },
    "71049ed5-f140-520a-9ddf-bcf62549ceef": {
      "type": "institute",
      "label": "institute-021",
      "logo": "assets/logos/institute-021.svg",
      "cover": null,
      "gallery": []
    },
    "8c5586b8-732f-5664-a62d-db47b32f7d7c": {
      "type": "government_school",
      "label": "gov-school-011",
      "logo": "assets/logos/gov-school-011.svg",
      "cover": null,
      "gallery": []
    },
    "686787f6-6068-5790-bf0d-2be5d03a0aac": {
      "type": "private_school",
      "label": "school-001",
      "logo": "assets/logos/school-001.svg",
      "cover": null,
      "gallery": []
    },
    "c5521ca1-979a-5259-b402-378d7f0f9211": {
      "type": "college",
      "label": "college-034",
      "logo": "assets/logos/college-034.svg",
      "cover": null,
      "gallery": []
    },
    "03c51a86-36df-58f0-b38c-50f488751053": {
      "type": "institute",
      "label": "institute-024",
      "logo": "assets/logos/institute-024.svg",
      "cover": null,
      "gallery": []
    },
    "6016bf2f-6294-5af6-a3ec-56089228e8b5": {
      "type": "government_school",
      "label": "gov-school-012",
      "logo": "assets/logos/gov-school-012.svg",
      "cover": null,
      "gallery": []
    },
    "43e206ac-cb4a-516d-8f4e-14db95c59f74": {
      "type": "private_school",
      "label": "school-002",
      "logo": "assets/logos/school-002.svg",
      "cover": null,
      "gallery": []
    },
    "3a3bd620-548c-5452-8c24-63239fd8da2e": {
      "type": "institute",
      "label": "institute-022",
      "logo": "assets/logos/institute-022.svg",
      "cover": null,
      "gallery": []
    },
    "b6ab0dc6-f138-5b52-b86b-ed0c34db3fed": {
      "type": "private_school",
      "label": "school-004",
      "logo": "assets/logos/school-004.svg",
      "cover": null,
      "gallery": []
    },
    "b2f7e513-d465-59d4-b36b-4df01b9808b9": {
      "type": "university",
      "label": "university-033",
      "logo": "assets/logos/university-033.svg",
      "cover": null,
      "gallery": []
    },
    "99d9b4ee-d949-5af9-b712-485f4793f467": {
      "type": "government_school",
      "label": "gov-school-013",
      "logo": "assets/logos/gov-school-013.svg",
      "cover": null,
      "gallery": []
    },
    "3d4a7187-306c-54ee-9b97-5bb6a9ab1de6": {
      "type": "college",
      "label": "college-032",
      "logo": "assets/logos/college-032.svg",
      "cover": null,
      "gallery": []
    },
    "b65e78be-f73e-5b34-a3d8-ed410f176088": {
      "type": "institute",
      "label": "institute-023",
      "logo": "assets/logos/institute-023.svg",
      "cover": null,
      "gallery": []
    },
    "041a84c5-922d-556f-aa36-90c010da3ee7": {
      "type": "private_school",
      "label": "school-003",
      "logo": "assets/logos/school-003.svg",
      "cover": null,
      "gallery": []
    },
    "8c228c44-d6ab-54e6-942a-a4bb4cf02b0f": {
      "type": "government_school",
      "label": "gov-school-014",
      "logo": "assets/logos/gov-school-014.svg",
      "cover": null,
      "gallery": []
    },
    "f6c108fe-8fcc-5b67-91eb-0fa23e23eca1": {
      "type": "college",
      "label": "college-037",
      "logo": "assets/logos/college-037.svg",
      "cover": null,
      "gallery": []
    },
    "e11aee29-f408-546f-bbe1-1385f447050f": {
      "type": "government_school",
      "label": "gov-school-015",
      "logo": "assets/logos/gov-school-015.svg",
      "cover": null,
      "gallery": []
    },
    "7c26e282-9586-544d-b1dc-66901438e258": {
      "type": "college",
      "label": "college-036",
      "logo": "assets/logos/college-036.svg",
      "cover": null,
      "gallery": []
    },
    "8bf27b96-bb09-5ad9-b8fc-30e54f3157f3": {
      "type": "institute",
      "label": "institute-025",
      "logo": "assets/logos/institute-025.svg",
      "cover": null,
      "gallery": []
    },
    "1e981b6a-8b4c-591d-b1b1-88ffdc6a0b54": {
      "type": "private_school",
      "label": "school-005",
      "logo": "assets/logos/school-005.svg",
      "cover": null,
      "gallery": []
    },
    "118f3328-bc82-5d10-a28d-058bfca8c87e": {
      "type": "government_school",
      "label": "gov-school-016",
      "logo": "assets/logos/gov-school-016.svg",
      "cover": null,
      "gallery": []
    },
    "d7021d31-ac55-57f2-95f0-a8c89a27af1c": {
      "type": "university",
      "label": "university-035",
      "logo": "assets/logos/university-035.svg",
      "cover": null,
      "gallery": []
    },
    "9d863d93-5d3e-53ee-99d5-8e9469a4339e": {
      "type": "institute",
      "label": "institute-026",
      "logo": "assets/logos/institute-026.svg",
      "cover": null,
      "gallery": []
    },
    "76ca8f67-a968-5aab-95ac-bc172202e359": {
      "type": "private_school",
      "label": "school-006",
      "logo": "assets/logos/school-006.svg",
      "cover": null,
      "gallery": []
    },
    "04a0c0d0-c263-55dc-871e-5bac65127344": {
      "type": "institute",
      "label": "institute-027",
      "logo": "assets/logos/institute-027.svg",
      "cover": null,
      "gallery": []
    },
    "2de4aab4-2390-5a83-a99e-7b37b54f87d7": {
      "type": "private_school",
      "label": "school-007",
      "logo": "assets/logos/school-007.svg",
      "cover": null,
      "gallery": []
    },
    "33ca04c7-7f13-5647-915c-ba10e778e128": {
      "type": "institute",
      "label": "institute-028",
      "logo": "assets/logos/institute-028.svg",
      "cover": null,
      "gallery": []
    },
    "6f90e1c9-77d3-5e2a-bacc-377457d03226": {
      "type": "government_school",
      "label": "gov-school-017",
      "logo": "assets/logos/gov-school-017.svg",
      "cover": null,
      "gallery": []
    },
    "5c2581da-58cf-56ae-8449-0d744adf2054": {
      "type": "government_school",
      "label": "gov-school-018",
      "logo": "assets/logos/gov-school-018.svg",
      "cover": null,
      "gallery": []
    },
    "9450e834-6c75-512d-8e56-b5679cdeeff8": {
      "type": "university",
      "label": "university-038",
      "logo": "assets/logos/university-038.svg",
      "cover": null,
      "gallery": []
    },
    "41743719-85f3-5f02-be06-30fc686dec51": {
      "type": "institute",
      "label": "institute-029",
      "logo": "assets/logos/institute-029.svg",
      "cover": null,
      "gallery": []
    },
    "098723b1-d794-59e3-866e-70a789c56746": {
      "type": "government_school",
      "label": "gov-school-019",
      "logo": "assets/logos/gov-school-019.svg",
      "cover": null,
      "gallery": []
    },
    "8b28839e-b5fe-5a07-a575-98e5cabe3028": {
      "type": "private_school",
      "label": "school-008",
      "logo": "assets/logos/school-008.svg",
      "cover": null,
      "gallery": []
    },
    "5f9cada6-e0de-578a-9f69-f8a2a8ab6de8": {
      "type": "college",
      "label": "college-039",
      "logo": "assets/logos/college-039.svg",
      "cover": null,
      "gallery": []
    },
    "bd6e34e3-fde3-51e9-a457-c7eaf97003a4": {
      "type": "private_school",
      "label": "school-009",
      "logo": "assets/logos/school-009.svg",
      "cover": null,
      "gallery": []
    },
    "721fe86e-96bf-53ce-8557-da88cf7b4ad5": {
      "type": "college",
      "label": "college-040",
      "logo": "assets/logos/college-040.svg",
      "cover": null,
      "gallery": []
    },
    "d1b23a4b-bc8e-5258-94d4-8518ec6cfe5d": {
      "type": "institute",
      "label": "institute-030",
      "logo": "assets/logos/institute-030.svg",
      "cover": null,
      "gallery": []
    },
    "bbcb6ef7-8462-57a3-b0d1-31964ac6b80b": {
      "type": "government_school",
      "label": "gov-school-020",
      "logo": "assets/logos/gov-school-020.svg",
      "cover": null,
      "gallery": []
    },
    "17a46cd5-cbb9-5cd1-adc5-51e30bbe4c14": {
      "type": "private_school",
      "label": "school-010",
      "logo": "assets/logos/school-010.svg",
      "cover": null,
      "gallery": []
    }
  },
  "teachers": {
    "24c4e156-615c-4e11-900d-6c6966c558e0": {
      "gender": "male",
      "userId": "181352d2-78be-40b5-a0d3-267d1a336ad7",
      "avatar": null,
      "cover": null,
      "gallery": []
    }
  },
  "users": {},
  "owners": {}
};
